### ISSUE TITLE
sl6, f26 :: error building gcc

### ISSUE THREAD

**Issue by adriansev** [alisw/alidist#969] opened 2017-12-14 09:24 UTC
aliBuild does not work on centos 6, i get 
DEBUG:AliPhysics:GCC-Toolchain:ali-latest: /software/physics-tools/ALIBUILD/sw/sw/SPECS/slc6_x86-64/GCC-Toolchain/v4.9.3-alice3-1/GCC-Toolchain.sh: line 27: ../binutils/configure: Not a directory 
see the gcc log that can be found here :
http://issaf.spacescience.ro/adrian/alibuild/

also does not work on fedora 26 where compilation breaks on binutils of gcc
the log is here https://sev.spacescience.ro/adrian/alibuild/

on fedora 26 i tried to force the usage of local gcc (i just increased the max condition in gcc recipe) but then gsoap give compilation error ..

What OS is supported for certain? is it possible to use docker on fedora 26?
is https://alisw.github.io/alibuild/user.html#running-in-docker all i need to know to run in docker?
Thank you!

**Comment by dberzano** [comment] 2018-02-14 15:42
Closing as this ticket is old and we cannot reproduce it (the GCC version under `/cvmfs/alice.cern.ch/etc/toolchain/modulefiles/el6-x86_64/Toolchain` was produced using the recipes that fail for you, on SLC6).

**Closed by dberzano** 2018-02-14 15:42 UTC
