### ISSUE TITLE
ALICE O2 build fails on CC7 with python 2.7.10 error (freetype)

### ISSUE THREAD

**Issue by vascobarroso** [alisw/alidist#283] opened 2016-04-07 13:25 UTC
See [log](https://github.com/alisw/alidist/files/208458/log.txt).

Also, the message "Building our own python. If you want to avoid this, please install python >= 2.7" is strange since we have in the system python 2.7.8 enabled (via devtoolset).

> [vasco@aidrefflp01 o2Tutorial]$ python --version
> Python 2.7.8
> [vasco@aidrefflp01 o2Tutorial]$

**Comment by Barthelemy** [comment] 2016-04-07 14:02
To be noted that it seems to be a problem with pkgconfig although I see the proper config : 

>
[bvonhall@aidrefflp01 alice]$ more /usr/lib64/pkgconfig/freetype2.pc
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include
>
Name: FreeType 2
Description: A free, high-quality, and portable font engine.
Version: 16.0.10
Requires:
Libs: -L${libdir} -lfreetype
Libs.private:   
Cflags: -I${includedir}/freetype2 -I${includedir}

**Comment by ktf** [comment] 2016-04-07 14:04
Regarding the pig-config part, I will check. We had some fix in the past, but maybe it does not work for slc6.

Regarding the second question. Can you run:

```
alibuild/aliDoctor | grep -i python
```

and tell me what it says? I suspect you are missing the certifi module. As noted in #265 we should allow to pickup python from the system and only rebuild the modules it lacks.

**Comment by vascobarroso** [comment] 2016-04-07 14:10
Please notice that this is a CC7 setup, not SLC6.
Here's the output:

> [vasco@aidrefflp01 o2Tutorial]$ alibuild/aliDoctor | grep -i python
> /bin/sh: brew: command not found
> /bin/sh: brew: command not found
> /bin/sh: brew: command not found
> <stdin>:3:2: error: #error "Cannot use system's boost."
> <stdin>:2:2: error: #error "Cannot use system's, GCC building our own."
> /bin/sh: brew: command not found
> <stdin>:1:29: fatal error: gsl/gsl_version.h: No such file or directory
> compilation terminated.
> /bin/sh: brew: command not found
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: No module named matplotlib
> /bin/sh: brew: command not found
> /bin/sh: brew: command not found
> <stdin>:1:27: fatal error: yaml-cpp/yaml.h: No such file or directory
> compilation terminated.
> /bin/sh: brew: command not found
> Reading alidist/python.sh
> Python:python -c 'import matplotlib; import numpy; import certifi ; import sys; sys.exit(1 if sys.version_info < (2, 7) else 0)'
> Python:
> Python: exit code 1

**Comment by ktf** [comment] 2016-04-07 15:11
Indeed you are lacking matplotlib numpy and certifi . Will try to adapt the recipe so that only the python modules get rebuilt.

**Comment by Barthelemy** [comment] 2016-04-20 06:25
I think that I have the same error on SLC6. You can test it here : 
eulisse@pcald02a:/alice

> ./alibuild/aliBuild build o2 --disable GEANT4,GEANT3,GEANT_VMC

**Comment by ktf** [comment] 2016-04-20 09:06
I think I've fixed this as part of #305. I managed to compile successfully on `pcald02a`. Now testing everywhere and then I will merge it.

**Comment by Barthelemy** [comment] 2016-04-20 09:28
cool

**Comment by ktf** [comment] 2016-04-20 15:04
Closing as duplicate of #305.

**Closed by ktf** 2016-04-20 15:04 UTC
Labels: 5 - In production
