### ISSUE TITLE
Error building O2 on Ubuntu 16.4

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alidist#417] opened 2016-06-02 07:01 UTC
When building python-modules it fails : 
1. one must install libfreetype-devel and libpng-devel. Shouldn't this be install automatically ?
2. then it fails to install : 

> error: can't create or remove files in install directory
> 
> The following error occurred while trying to add or remove files in the
> installation directory:
> 
> ```
> [Errno 2] No such file or directory: '/home/bvonhall/alice/sw/INSTALLROOT/986ce42cf366731c4e22ce62717598308c1f36ff/ubuntu1604_x86-64/Python-modules/1.0-1/lib/python2.7/site-packages/test-easy-install-3158.write-test'
> ```
> 
> The installation directory you specified (via --install-dir, --prefix, or
> the distutils default setting) was:
> 
> ```
> /home/bvonhall/alice/sw/INSTALLROOT/986ce42cf366731c4e22ce62717598308c1f36ff/ubuntu1604_x86-64/Python-modules/1.0-1/lib/python2.7/site-packages/
> ```
> 
> This directory does not currently exist.  Please create it and try again, or
> choose a different installation directory (using the -d or --install-dir
> option).

[log.txt](https://github.com/alisw/alidist/files/295002/log.txt)

**Comment by ktf** [comment] 2016-06-02 07:24
#418 should fix the issue issue with libpng / freetype, although you are probably better off picking them up from the system (the latest greatest aliDoctor will actually be able to tell you what you are missing for a given package if you say `aliDoctor O2`). For the second part, I will try to reproduce.

**Comment by Barthelemy** [comment] 2016-06-16 12:16
1. good
2. disappeared
3. New problem with gSoap. It is installed and alidoctor does not report that it will build it. When it builds it nevertheless, it fails (see attachment). 
[log.txt](https://github.com/alisw/alidist/files/318324/log.txt)

**Comment by ktf** [comment] 2017-08-09 08:14
Closing this as I assume this was fixed (I know people are using O2 on Ubuntu nowadays). Please open a new ticket (with a more specific error) if not the case.

**Closed by ktf** 2017-08-09 08:14 UTC
